### ISSUE TITLE
An error i found in readme.md

### ISSUE THREAD

**Issue by larryzhuo** [openstf/STFService.apk#11]
I try to connect Agent like this accord readme.md
```bash
     adb forward tcp:1090 tcp:1090
     nc localhost 1090
```
but there are not any binary output.

the i read the code, and try those cmd
```bash
     adb forward tcp:1090 localabstract:stfagent
     nc localhost 1090
```
then i can get those output in terminal
```bash
     Listening on @stfagent
     InputClient started
     InputClient closing
```

am i right?

**Comment by sorccu** [comment]
You are correct, this changed some time ago.

**Comment by sorccu** [comment]
Should be up to date now!
