### ISSUE TITLE
Can STF allow manual actions on multiple devices

### ISSUE THREAD

**Issue by saikrishna321** [openstf/STFService.apk#12]
@sorccu 

Use Case:

Action done on one device should reflect on all the connected client devices. Is this possible?

**Comment by sorccu** [comment]
It's possible but too much effort.

Think about it. Let's say you have a Galaxy S6, a Nexus 5X, a Xiaomi Mi 5
and a Nexus 9. You're in the home screen. User presses the Chrome icon on
Nexus 5X.

What is supposed to happen? All these devices have different resolutions.
They have different skins. Pressing the same relative coordinate on each
device is possible, but there's no guarantee that it'll press the same
thing on each device.

You could inspect the view hierarchy, but then you run into other issues.
Perhaps the Chrome icon is not even visible? What do you do, randomly swipe
left/right/up/down and hope to find it? On the S6, the icon is for a
Samsung browser, not Chrome, what do you do? On the Xiaomi, you don't even
have Chrome installed at all, what do you do?

Now think about differences between alerts, permission prompts, system
notifications, apps with responsive layouts responding to differences in
real estate, and you have a recipe for a disaster. It's borderline
impossible to do it reliably, much less in real time. Companies with tens
of millions in revenue still have not fully solved this problem.

Now think that we work on this project for free on our own time. Do you
think we're going to have time to make it?

Pull requests are accepted.

**Comment by saikrishna321** [comment]
@sorccu appreciate the explanation. I'm sure there is lot of time that needs to get in. Thanks for this awesome project build :)
