### ISSUE TITLE
Service Request's meaning

### ISSUE THREAD

**Issue by yihchu** [openstf/STFService.apk#14]
Many service requests' meaning is not clear... and no explanation, so we can't know the function, like DO_IDENTIFY and so on. And many parameters' meaning is not clear.

**Comment by sorccu** [comment]
You have to read the STF source code. In principle, we are unable to answer
questions that are too broad (e.g. explain all requests) because that takea
way too much time. You have to have a more specific request (e.g. just ask
about DO_IDENTIFY).
