### ISSUE TITLE
STFService with Internet

### ISSUE THREAD

**Issue by Phelan164** [openstf/STFService.apk#17]
I have STFServer running online (I rent a PC on cloud then run STFServer).
Is this possible to connect my phone to the STFServer via Internet?
(I just connect successfully via USB or same WiFi router)

**Comment by BeiKeJieDeLiuLangMao** [comment]
Maybe you could use remote adb

**Comment by Phelan164** [comment]
Could you guide me detail?

**Comment by BeiKeJieDeLiuLangMao** [comment]
firstly, you need open phone‘s remote adb model by command "adb tcpip 5555"
then you need connect to this device by "adb connect <ip>:5555" at the pc which you want to connect to stfService
after that you could use stfService like device via USB

**Comment by Phelan164** [comment]
Your method, I tried to connect my phone to my stf server PC. in which, both my phone and stf server PC connect same WiFi router. It is OK.

BUT, my case:
- my phone use 3g
- my PC connect WiFi router.
Is this possible to connect my phone to stf server?

**Comment by sorccu** [comment]
No, that's not a supported use case. STF requires additional permissions that only the adb shell has. It won't work without adb.

**Comment by amet123** [comment]
How headspin work

**Comment by thinkhy** [comment]
it can be supported if you have a public domain/ip

**Comment by imran-abbas1** [comment]
@thinkhy i have a public ip. can you tell me how to make this work?
