### ISSUE TITLE
Bluetooth and location

### ISSUE THREAD

**Issue by JeannedArk** [openstf/STFService.apk#18]
Hi,

first of all, you did a great job!

We would like to be able on the OpenSTF server to reset Bluetooth and location settings. As far as I have seen there exists no functionality for these already. I would create then similiar ones to the WiFi functionality:
https://github.com/openstf/STFService.apk/blob/master/app/src/main/java/jp/co/cyberagent/stf/query/SetWifiEnabledResponder.java

I think that might be useful to others, therefore after finishing this feature shall I create a pull request?

Thanks

**Comment by sorccu** [comment]
Yes please :)

**Comment by JeannedArk** [comment]
I created a pull request for Bluetooth:
https://github.com/openstf/STFService.apk/pull/20/files

Apparently, it is not able to change the location settings programmatically for security reasons:
https://stackoverflow.com/questions/4721449/how-can-i-enable-or-disable-the-gps-programmatically-on-android

**Comment by JeannedArk** [comment]
Ping @sorccu , maybe you had already a chance to have a look at the code changes :)

**Comment by sorccu** [comment]
I can't until next weekend - sorry for the delay.

**Comment by JeannedArk** [comment]
@sorccu Any chance to test it?

**Comment by sorccu** [comment]
Finally merged. Sorry for the wait.
