### ISSUE TITLE
Hello, the compilation process encountered an error, please help Thank you

### ISSUE THREAD

**Issue by WanyueKJ** [openstf/STFService.apk#3]
When I run assembleDebug./gradlew, the following error prompts
/Users/weilian/STFService.apk/proto/build/generated-sources/main/jp/co/cyberagent/stf/proto/Wire.java:30251: error: package com.google.protobuf.GeneratedMessageV3 does not exist

**Comment by advance19899** [comment]
已经解决了 brew install protoc  是安装的3.1.0   需要手动安装protoc 2.6.1 就可以了
