### ISSUE TITLE
In jp.co.cyberagent.stf.Service import jp.co.cyberagent.stf.proto.Wire class is not exist

### ISSUE THREAD

**Issue by uniquker** [openstf/STFService.apk#37]
In jp.co.cyberagent.stf.Service
import jp.co.cyberagent.stf.proto.Wire class is not exist,
Excuse me, what's the reason?
![image](https://user-images.githubusercontent.com/15793551/59587495-f871e580-9117-11e9-9218-284e6be9c69e.png)

**Comment by sorccu** [comment]
It gets generated automatically. If not, your setup is broken somehow.

**Comment by ytpeng105** [comment]
遇到这种问题怎么解决？
how to resolve this problem
