### ISSUE TITLE
does not support protobuf 3.0.0

### ISSUE THREAD

**Issue by edwardZj** [openstf/STFService.apk#5]
protobuf in project is old.2.6.1
but I install protobuf 3.0.0     so when I build the project,that cames error 程序包com.google.protobuf.GeneratedMessageV3不存在 which means GeneratedMessageV3 does not exist. So I changed the protobuf version in project to 3.0.0.  But too manay error need be fixed.So I
report this issue.

**Comment by bestfc** [comment]
maybe it just happened in windows.
I have the same errors.

**Comment by codeskyblue** [comment]
+1 got the same error too

**Comment by xinyu0601** [comment]
I got the same error on ubuntu too

**Comment by codeskyblue** [comment]
have to use protoc 2.6.0.

For windows protoc can be download from here https://sourceforge.net/projects/protobuf/files/protoc-2.6.0-win32.zip/download

**Comment by bestfc** [comment]
yes,do it with the same version.I have corrected it in this way

**Comment by ghost** [comment]
@codeskyblue , I do it in your way, it works

**Comment by sorccu** [comment]
You don't need to install protoc in the latest version anymore. It now uses com.google.protobuf:protoc-gen-javalite to download it automatically.
