### ISSUE TITLE
how to debug in Agent.java

### ISSUE THREAD

**Issue by larryzhuo** [openstf/STFService.apk#9]
I have add some code in agent. but i don't know how to debug it. if it was in some activity like IdentityActivity.java, I can use Toast.makeToaster.

sorry, I am not a android developer

**Comment by sorccu** [comment]
You can use `System.err.println("message")` and just look at the output. No alerts in the UI.

**Comment by sorccu** [comment]
You should also be able to bind the Android Studio debugger to the process and set a breakpoint somewhere.

**Comment by larryzhuo** [comment]
ok. thank you
